<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-D50246KN" failures="1" tests="5" name="com.qa.crm.tests.AccountPageTest" time="100.402" errors="0" timestamp="2021-04-18T18:32:23 IST" skipped="0">
  <testcase classname="com.qa.crm.tests.AccountPageTest" name="accountPageHeaderTest" time="11.813">
    <failure message="expected [Manage your preferences] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Manage your preferences] but found [null]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.qa.crm.tests.AccountPageTest.accountPageHeaderTest(AccountPageTest.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- accountPageHeaderTest -->
  <system-out/>
  <testcase classname="com.qa.crm.tests.AccountPageTest" name="accountAddTest" time="11.426"/>
  <system-out/>
  <testcase classname="com.qa.crm.tests.AccountPageTest" name="accountAddTest" time="58.267"/>
  <system-out/>
  <testcase classname="com.qa.crm.tests.AccountPageTest" name="accountAddTest" time="10.123"/>
  <system-out/>
  <testcase classname="com.qa.crm.tests.AccountPageTest" name="accountAddTest" time="8.773"/>
  <system-out/>
</testsuite> <!-- com.qa.crm.tests.AccountPageTest -->
